# Generated by Django 4.0.6 on 2022-08-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_alter_drone_name_alter_dronecategory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='has_it_completed',
            new_name='has_it_competed',
        ),
    ]
